workflow:
  name: '$PIPELINE_TYPE:$CI_COMMIT_REF_NAME'
  rules:
    - if: $ENABLE_GITINGEST == "1"
      variables:
        PIPELINE_TYPE: 'gitingest'
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        PIPELINE_TYPE: 'default'
    - if: $CI_COMMIT_REF_PROTECTED == "true"
      variables:
        PIPELINE_TYPE: 'default'
    - if: $CI_COMMIT_TAG
      variables:
        PIPELINE_TYPE: 'default'
    - when: never

stages:
    - orchestrate

default-pipeline:
    stage: orchestrate
    trigger:
        include:
            - local: '.cicd/pipelines/default.yml'
        strategy: depend
    rules:
        - if: $PIPELINE_TYPE == "default"

gitingest-pipeline:
    stage: orchestrate
    trigger:
        include:
            - local: '.cicd/pipelines/gitingest.yml'
        strategy: depend
    rules:
        - if: $PIPELINE_TYPE == "gitingest"
