# .pre-commit-config.yaml
ci:
  autoupdate_schedule: quarterly

default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: local
    hooks:
      - id: gitlab-ci-verify
        name: gitlab-ci-verify
        entry: gitlab-ci-verify --gitlab-ci-file .gitlab-ci.yml --no-lint-api --severity error --format json --output gitlab_ci_verify_report.json -E SC-1073,SC-1065,SC-1064,SC-1072
        language: python
        additional_dependencies: [gitlab-ci-verify==2.10.0]
        pass_filenames: false
        files: ^(\.gitlab-ci\.ya?ml|\.cicd/jobs/.*\.ya?ml)$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff-check
        args: [--fix, --show-fixes]
        files: ^(darts|tests|helper_scripts|\.cicd)/.*\.py$
      - id: ruff-format
        files: ^(darts|tests|helper_scripts|\.cicd)/.*\.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
        files: ^((.cicd|helper_scripts)/.*\.ya?ml|\.gitlab-ci\.ya?ml)$
        exclude: ^(\.gitlab-ci\.ya?ml|\.cicd/jobs/.*\.ya?ml)$
      - id: check-toml
        files: ^[^/]+\.toml$
      - id: mixed-line-ending
      - id: detect-private-key
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: check-merge-conflict
