# od_emit_template_instantiations
# ------------------------------------------------------------------------------
# Generate a `.inc` file with explicit template-class instantiation directives
# `template class <CLASS><N>;` for N in [1..MAX_N]. Solver source files include
# the generated `.inc` from inside the class's namespace so the C++ source stays
# free of hand-maintained N=1..N=N walls of `template class` lines that have to
# be kept in sync with the CMake build configuration.
#
# Designed to be reusable: any solver template parameterized by a single
# integer (block size / N_VARS) can drive its instantiation set off the same
# OPENDARTS_MAX_DIMS knob (or a different bound) via this helper.
#
# Required arguments:
#   CLASS        Unqualified template class name (e.g. linsolv_superlu).
#   MAX_N        Upper bound (inclusive). The file emits N=MIN_N..MAX_N.
#   OUTPUT_FILE  Absolute path to the .inc file to write.
#
# Optional arguments:
#   MIN_N        Lower bound (inclusive). Defaults to 1. Use a higher value for
#                solvers whose smallest meaningful block size is > 1 (e.g.
#                linsolv_bos_cpr starts at 2 — the constrained-pressure-residual
#                split is undefined for a 1x1 block).
#
# The emitted file contains only `template class CLASS<N>;` lines plus a header
# comment; it does not open or close any namespace. The consumer must `#include`
# it from inside the namespace declaring CLASS so the directives apply to the
# right symbol.
#
# Behaves like configure_file with @ONLY semantics: the output is rewritten only
# when its content changes, so CMake re-runs don't trigger spurious full rebuilds
# of the consuming TU.

function(od_emit_template_instantiations)
  set(_one CLASS MIN_N MAX_N OUTPUT_FILE)
  cmake_parse_arguments(_OD "" "${_one}" "" ${ARGN})

  if(NOT _OD_CLASS)
    message(FATAL_ERROR "od_emit_template_instantiations: CLASS is required")
  endif()
  if(NOT _OD_MAX_N)
    message(FATAL_ERROR "od_emit_template_instantiations: MAX_N is required")
  endif()
  if(NOT _OD_OUTPUT_FILE)
    message(FATAL_ERROR "od_emit_template_instantiations: OUTPUT_FILE is required")
  endif()
  if(NOT DEFINED _OD_MIN_N)
    set(_OD_MIN_N 1)
  endif()
  if(NOT _OD_MIN_N MATCHES "^[1-9][0-9]*$")
    message(FATAL_ERROR "od_emit_template_instantiations: MIN_N must be a positive integer (got '${_OD_MIN_N}')")
  endif()
  if(NOT _OD_MAX_N MATCHES "^[1-9][0-9]*$")
    message(FATAL_ERROR "od_emit_template_instantiations: MAX_N must be a positive integer (got '${_OD_MAX_N}')")
  endif()
  if(_OD_MIN_N GREATER _OD_MAX_N)
    message(FATAL_ERROR "od_emit_template_instantiations: MIN_N (${_OD_MIN_N}) must not exceed MAX_N (${_OD_MAX_N})")
  endif()

  set(_header
"// Auto-generated by od_emit_template_instantiations() — DO NOT EDIT.\n// Range: ${_OD_CLASS}<${_OD_MIN_N}> .. ${_OD_CLASS}<${_OD_MAX_N}>.\n// #include from inside the namespace declaring ${_OD_CLASS}.\n\n")
  set(_body "")
  foreach(_n RANGE ${_OD_MIN_N} ${_OD_MAX_N})
    set(_body "${_body}template class ${_OD_CLASS}<${_n}>;\n")
  endforeach()
  set(_content "${_header}${_body}")

  # Idempotent write: avoid touching the file (and re-triggering rebuilds) when
  # the content hasn't changed across CMake re-configures.
  set(_should_write ON)
  if(EXISTS "${_OD_OUTPUT_FILE}")
    file(READ "${_OD_OUTPUT_FILE}" _existing)
    if("${_existing}" STREQUAL "${_content}")
      set(_should_write OFF)
    endif()
  endif()
  if(_should_write)
    file(WRITE "${_OD_OUTPUT_FILE}" "${_content}")
  endif()
endfunction()
