import os
import platform

import numpy as np
import pandas as pd

WELL_TIME_SERIES_FILENAME = "well_time_data.pkl"
WELL_TIME_SERIES_REFERENCE_ROWS = 20


def get_pkl_suffix():
    """
    Return the solver/platform suffix used for well time-series reference files.
    """
    if os.getenv("TEST_GPU") == "1":
        return "_gpu"
    if os.getenv("ODLS") == "-a":
        return "_iter"
    return "_odls"


def snapshot_well_time_series_files(root_dir: str):
    """
    Create a snapshot of existing well time-series files.

    :param root_dir: Directory in which well time-series files are searched recursively.
    """
    snapshot = {}
    if not os.path.isdir(root_dir):
        return snapshot

    for current_root, _, files in os.walk(root_dir):
        if WELL_TIME_SERIES_FILENAME not in files:
            continue
        path = os.path.join(current_root, WELL_TIME_SERIES_FILENAME)
        rel_path = os.path.relpath(path, root_dir)
        try:
            stat = os.stat(path)
        except OSError:
            continue
        snapshot[rel_path] = (stat.st_mtime_ns, stat.st_size)
    return snapshot


def changed_well_time_series_files(root_dir: str, before_snapshot: dict):
    """
    Find well time-series files created or updated after a previous snapshot.

    :param root_dir: Directory in which well time-series files are searched recursively.
    :param before_snapshot: Snapshot returned by :func:`snapshot_well_time_series_files` before running a test.
    """
    changed = []
    after_snapshot = snapshot_well_time_series_files(root_dir)
    for rel_path, file_state in after_snapshot.items():
        if before_snapshot.get(rel_path) != file_state:
            changed.append(os.path.join(root_dir, rel_path))
    return sorted(changed)


def compare_generated_well_time_series(
    root_dir: str,
    before_snapshot: dict,
    overwrite: int | str = 0,
    pkl_suffix: str = "",
):
    """
    Compare all well time-series files generated by one test run.

    :param root_dir: Directory in which well time-series files are searched recursively.
    :param before_snapshot: Snapshot returned by :func:`snapshot_well_time_series_files` before running a test.
    :param overwrite: Flag to overwrite reference files with generated well time-series files.
    :param pkl_suffix: Solver/platform suffix used in the reference file name.
    """
    failed = 0
    for time_series_file in changed_well_time_series_files(root_dir, before_snapshot):
        failed += compare_well_time_series(
            time_series_file, root_dir, overwrite, pkl_suffix
        )
    return 1 if failed else 0


def compare_well_time_series(
    time_series_file: str,
    model_dir: str,
    overwrite: int | str = 0,
    pkl_suffix: str = "",
):
    """
    Compare one generated well time-series pickle with its reference pickle.

    :param time_series_file: Generated ``well_time_data.pkl`` file.
    :param model_dir: Model directory containing the ``ref`` folder.
    :param overwrite: Flag to overwrite the reference file with the generated well time-series file.
    :param pkl_suffix: Solver/platform suffix used in the reference file name.
    """
    reference_file = get_well_time_series_reference_file(
        time_series_file, model_dir, pkl_suffix
    )
    overwrite = str(overwrite) == "1" or overwrite is True

    if overwrite:
        os.makedirs(os.path.dirname(reference_file), exist_ok=True)
        current = get_well_time_series_reference_slice(pd.read_pickle(time_series_file))
        current.to_pickle(reference_file)
        print("SAVED WELL TIME-SERIES PKL FILE", reference_file)
        return 0

    if not os.path.exists(reference_file):
        print("WELL TIME-SERIES PKL FILE", reference_file, "does not exist.")
        print("Run with UPLOAD_PKL=1 to create or update this reference file.")
        return 1

    reference = get_well_time_series_reference_slice(pd.read_pickle(reference_file))
    current = get_well_time_series_reference_slice(pd.read_pickle(time_series_file))
    return compare_well_time_series_frames(
        current, reference, time_series_file, reference_file
    )


def get_well_time_series_reference_file(
    time_series_file: str, model_dir: str, pkl_suffix: str = ""
):
    """
    Build the reference pickle path for a generated well time-series file.

    :param time_series_file: Generated ``well_time_data.pkl`` file.
    :param model_dir: Model directory containing the ``ref`` folder.
    :param pkl_suffix: Solver/platform suffix used in the reference file name.
    """
    rel_parent = os.path.dirname(os.path.relpath(time_series_file, model_dir))
    label = _reference_label(rel_parent)
    filename = "well_time_data_" + platform.system().lower()[:3] + pkl_suffix
    if label:
        filename += "_" + label
    return os.path.join(model_dir, "ref", filename + ".pkl")


def compare_well_time_series_frames(
    current: pd.DataFrame | dict,
    reference: pd.DataFrame | dict,
    time_series_file: str,
    reference_file: str,
):
    """
    Compare current and reference well time-series data columns independently.

    :param current: Generated well time-series data.
    :param reference: Reference well time-series data.
    :param time_series_file: Generated well time-series file path, used for diagnostic messages.
    :param reference_file: Reference well time-series file path, used for diagnostic messages.
    """
    if not isinstance(current, pd.DataFrame):
        current = pd.DataFrame(current)
    if not isinstance(reference, pd.DataFrame):
        reference = pd.DataFrame(reference)

    rtol, atol = _comparison_tolerances()
    failed = 0

    current_keys = set(current.columns)
    reference_keys = set(reference.columns)

    missing_keys = sorted(reference_keys - current_keys, key=str)
    extra_keys = sorted(current_keys - reference_keys, key=str)
    if missing_keys:
        failed += 1
        print(
            f"#{failed} well time-series check failed: missing keys in {time_series_file}: "
            + ", ".join(map(str, missing_keys))
        )
    if extra_keys:
        failed += 1
        print(
            f"#{failed} well time-series check failed: extra keys in {time_series_file}: "
            + ", ".join(map(str, extra_keys))
        )

    for key in sorted(reference_keys & current_keys, key=str):
        ref = reference[key].to_numpy(dtype=float)
        cur = current[key].to_numpy(dtype=float)

        if ref.shape != cur.shape:
            failed += 1
            print(
                f"#{failed} well time-series check failed for key '{key}': "
                f"shape is {cur.shape}, reference shape is {ref.shape}"
            )
            continue

        close = np.isclose(cur, ref, rtol=rtol, atol=atol, equal_nan=True)
        if np.all(close):
            continue

        failed += 1
        first_idx = int(np.flatnonzero(~close)[0])
        diff_abs = np.abs(cur - ref)
        denom = np.maximum(np.abs(ref), np.finfo(float).eps)
        diff_rel = diff_abs / denom
        max_abs_idx = _nanargmax(diff_abs)
        max_abs = diff_abs[max_abs_idx] if max_abs_idx is not None else np.nan
        max_rel = _nanmax(diff_rel)
        print(
            f"#{failed} well time-series check failed for key '{key}': "
            f"max(abs(diff))={max_abs:.3E}, max(rel(diff))={max_rel:.3E}, "
            f"first differing index={first_idx}, "
            f"reference={ref[first_idx]:.16E}, current={cur[first_idx]:.16E}, "
            f"rtol={rtol:.1E}, atol={atol:.1E}"
        )

    if failed:
        print("FAIL well time-series comparison")
        print("  current:  ", time_series_file)
        print("  reference:", reference_file)
        return 1

    print(
        "OK (well time-series comparison)",
        os.path.relpath(time_series_file, os.getcwd()),
    )
    return 0


def get_well_time_series_reference_slice(data: pd.DataFrame | dict):
    """
    Return the rows used for stored well time-series reference comparisons.

    :param data: Well time-series data loaded from a pickle file.
    """
    if not isinstance(data, pd.DataFrame):
        data = pd.DataFrame(data)
    return data.head(WELL_TIME_SERIES_REFERENCE_ROWS)


def _reference_label(rel_parent: str):
    """
    Convert an output directory relative path to a reference filename label.

    :param rel_parent: Output directory path relative to the model directory.
    """
    if rel_parent in ("", ".", "output"):
        return ""
    return (
        rel_parent.replace("\\", "_")
        .replace("/", "_")
        .replace(" ", "_")
        .replace(":", "_")
    )


def _comparison_tolerances():
    """
    Return numeric comparison tolerances for the active test environment.
    """
    nt = int(os.environ.get("OMP_NUM_THREADS", 1))
    is_gpu = os.environ.get("TEST_GPU") == "1"
    if nt > 1 or is_gpu:
        # Well time-series rates are derived from stored well states and can show
        # small platform-dependent differences on GPU and multithreaded runs.
        return 1e-3, 1e-6
    return 1e-9, 1e-9


def _nanargmax(values: np.ndarray):
    """
    Return the index of the maximum value.

    :param values: Values to inspect.
    """
    if values.size == 0 or np.all(np.isnan(values)):
        return None
    return int(np.nanargmax(values))


def _nanmax(values: np.ndarray):
    """
    Return the maximum value.

    :param values: Values to inspect.
    """
    if values.size == 0 or np.all(np.isnan(values)):
        return np.nan
    return np.nanmax(values)
